# Generated by Django 5.1.4 on 2024-12-30 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomE', models.CharField(max_length=50)),
                ('prenomE', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_naissance_E', models.DateField()),
                ('date_embauche_E', models.DateField()),
                ('adresse_E', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_fonctionnalite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_formation', models.CharField(max_length=100)),
                ('description_formation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=100)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(max_length=50)),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_conge', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Offre_employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_offre', models.CharField(max_length=100)),
                ('code_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='app.service')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='code_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='app.service'),
        ),
    ]
