# Generated by Django 5.1.4 on 2024-12-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('code_fonctionnalite', models.AutoField(primary_key=True, serialize=False)),
                ('path_fonctionnalite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code_service', models.AutoField(primary_key=True, serialize=False)),
                ('description_service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('code_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nomE', models.CharField(max_length=50)),
                ('prenomE', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_naissance_E', models.DateField()),
                ('date_embauche_E', models.DateField()),
                ('adresse_E', models.CharField(max_length=100)),
                ('code_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employe')),
                ('code_fonctionnalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fonctionnalite')),
            ],
            options={
                'unique_together': {('code_employe', 'code_fonctionnalite')},
            },
        ),
    ]
