# Generated by Django 5.1.4 on 2024-12-28 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_conge', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='app.employe')),
            ],
        ),
    ]
