# Generated by Django 5.1.4 on 2025-01-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_critere', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='competence',
            name='nom_competence',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField()),
                ('note_evaluation_totale', models.FloatField()),
                ('type_evaluation', models.CharField(choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual')], default='Annual', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_employee', to='app.employe')),
                ('employe_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_manager', to='app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_CE', models.IntegerField()),
                ('code_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.competence')),
                ('code_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_developped', to='app.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluerCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_critere_evaluer', models.FloatField()),
                ('code_critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criterevaluation')),
                ('code_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectifAttient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attient', models.BooleanField(default=False)),
                ('code_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_attient', to='app.evaluation')),
                ('code_objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_attient', to='app.objectif')),
            ],
        ),
        migrations.CreateModel(
            name='RapportEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField()),
                ('contenu_rapport', models.TextField()),
                ('code_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='app.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='RapportPartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='app.employe')),
                ('code_rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='app.rapportevaluation')),
            ],
        ),
    ]
