# Generated by Django 5.1.2 on 2025-01-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=20)),
                ('salaire_quotidien', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prime_montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='app.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='app.salaire'),
        ),
    ]
