# Generated by Django 5.1.4 on 2024-12-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='competences',
            field=models.ManyToManyField(related_name='employes', to='app.competence'),
        ),
        migrations.AddField(
            model_name='employe',
            name='formations',
            field=models.ManyToManyField(related_name='employes', to='app.formation'),
        ),
    ]
