# Generated by Django 5.1.2 on 2025-01-09 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_salaire_absence_prime_employe_salaire_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('justifications', models.TextField(blank=True, null=True)),
                ('approuvee', models.BooleanField(default=False)),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_salaire', to='app.employe')),
            ],
        ),
    ]
