# Generated by Django 5.1.4 on 2024-12-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employe_competences_employe_formations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fonctionnalite',
        ),
    ]
