# Generated by Django 5.1.2 on 2025-01-10 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_demandeavancesalaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='prime',
            name='date_attribuee',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
