# Generated by Django 5.1.4 on 2024-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_fonctionnalite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Fonctionnalite', models.CharField(max_length=50)),
                ('path_fonctionnalite', models.CharField(max_length=100)),
            ],
        ),
    ]
