# Generated by Django 5.1.4 on 2024-12-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_competence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomC', models.CharField(max_length=100)),
                ('prenomC', models.CharField(max_length=100)),
                ('adresseC', models.TextField()),
                ('tlfn_candidat', models.CharField(max_length=20)),
            ],
        ),
    ]
