# Generated by Django 5.1.4 on 2024-12-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_objectif', models.TextField()),
                ('date_limite', models.DateField()),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='app.employe')),
            ],
        ),
    ]
