# Generated by Django 5.1.4 on 2025-01-10 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_prime_date_attribuee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employe')),
            ],
        ),
    ]
