# Generated by Django 5.1.4 on 2025-01-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_employe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
    ]
