# Generated by Django 5.1.4 on 2025-01-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_salaire_salaire_quotidien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='salaire_quotidien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
