# Generated by Django 5.1.4 on 2025-01-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_evaluation_note_evaluation_totale'),
        ('app', '0008_candidat_user'),
    ]

    operations = [
    ]
