# Generated by Django 5.1.4 on 2025-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrats à durée indéterminée'), ('CDD', ' contrats à durée déterminée'), ('Stage', 'stage')], max_length=100),
        ),
    ]
