# Generated by Django 5.1.4 on 2025-01-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250115_2032'),
        ('app', '0009_merge_20250115_2054'),
    ]

    operations = [
    ]
