# Generated by Django 5.1.4 on 2025-01-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contrat_type_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
