# Generated by Django 5.1.4 on 2025-01-17 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_favoris'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDePaieS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heures_supp', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('salaire_mensuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_de_paie', to='app.employe')),
            ],
        ),
        migrations.DeleteModel(
            name='FicheDePaie',
        ),
        migrations.AddConstraint(
            model_name='fichedepaies',
            constraint=models.UniqueConstraint(fields=('employe', 'month'), name='unique_salaire_per_month'),
        ),
    ]
