# Generated by Django 5.1.4 on 2024-12-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
