# Generated by Django 5.1.4 on 2024-12-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0002_conge_description_alter_conge_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conge',
        ),
    ]
