# Generated by Django 5.1.4 on 2025-01-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_customuser_candidat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='candidat',
        ),
    ]
