# Generated by Django 5.1.4 on 2025-01-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_customuser_candidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
