# Generated by Django 5.1.4 on 2025-01-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250115_2032'),
        ('authentification', '0009_alter_customuser_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.employe'),
        ),
    ]
